dist: trusty
sudo: required

before_script:
  - "export DISPLAY=:99.0"
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1920x1200x16"
  - sudo apt-get update
  - sudo apt-get install -y libappindicator1 fonts-liberation lftp
  - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb -O /tmp/chrome.deb
  - sudo dpkg -i /tmp/chrome.deb
  - wget https://chromedriver.storage.googleapis.com/2.29/chromedriver_linux64.zip -O /tmp/chromedriver.zip
  - unzip /tmp/chromedriver.zip -d /tmp/
  - sudo mv /tmp/chromedriver /usr/bin/chromedriver
  - export CHROMEDRIVER=/usr/bin/chromedriver
  - export CHROME_BIN=/usr/bin/google-chrome
  - "export DBUS_SESSION_BUS_ADDRESS=/dev/null"

script:
  - mvn clean install -Dwebtests.verbose=true -Dwebdriver.chrome.driver=$CHROMEDRIVER -Dwebtests.video.enabled=true -Dwebtests.video.dir=$PWD/web/target/videos

# Skip install step which is not needed with maven
install: true

cache:
 directories:
 - $HOME/.m2

jdk:
  - oraclejdk8